In [1]:
# Session 1 : Numpy Operations and Broadcastinig
#If increase all product price by 10%, how we update 10,000 values instantly

import numpy as np
price = np.array([100,200,300,400])
price * 1.10

array([110., 220., 330., 440.])

In [4]:
# Broadcasting Concept(Most Imp)

arr = np.array([[10,20,30],
             [40,50,60]])
arr + 5

array([[15, 25, 35],
       [45, 55, 65]])

In [7]:

# Indexing And Slicing

# 1D Indexing

arr = np.array([10,20,30,40,50])
arr[2]
arr[1:4]

array([20, 30, 40])

In [6]:
# 2D Indexing
arr = np.array([[10,20,30,40],[50,60,70,80]])
arr[1,2]

np.int64(70)

In [20]:
 # Scenario Based Questions

sales_day1 = np.array([120, 85, 60])       # Product A B C
sales_day2 = np.array([1250, 90, 75])

total_sales =  sales_day1 + sales_day2  
total_sales

Percentage = (sales_day2 - sales_day1)/ sales_day1 * 100 
Percentage

np.argmax(Percentage)      # argmax  ---->>> (return the index of max values )

np.int64(0)

In [31]:
# Weather data (Broadcasting)
temps = np.array([[25,28,30],
                  [22,24,26],
                  [30,32,33],
                  [27,29,31],
                  [20,21,23]])
temps

temps_f = temps * 9/5 + 32
temps_f

# array([[77. , 82.4, 86. ],
#        [71.6, 75.2, 78.8],
#        [86. , 89.6, 91.4],
#        [80.6, 84.2, 87.8],
#        [68. , 69.8, 73.4]])

correction = np.array([1,-1,0])
correction

adjust_temp = temps_f + correction
adjust_temp

array([[78. , 81.4, 86. ],
       [72.6, 74.2, 78.8],
       [87. , 88.6, 91.4],
       [81.6, 83.2, 87.8],
       [69. , 68.8, 73.4]])

In [35]:

# HealthCare Dataset(indexing)

bp = np.array([[120,80],
               [135,85],
               [140,90],
               [110,70],
               [125,75]])
bp

# Extract Systolic Values (First Column)
systolic = bp[:, 0] 
print(systolic)

# Find Patients with Systolic > 130 (Boolean Indexing)
high_bp = bp[bp[:, 0] > 130]
print(high_bp)

# Replace Diastolic < 80 with 80 (Minimum Threshold)
bp[bp[:, 1] < 80, 1] = 80
print(bp)

[120 135 140 110 125]
[[135  85]
 [140  90]]
[[120  80]
 [135  85]
 [140  90]
 [110  80]
 [125  80]]

In [43]:
# Agriculture Yield(Broadcasting + Indexing)

yields = np.array([[2.5,3.0,1.8],
                   [2.8,3.2,2.0],
                   [3.1,2.9,2.2],
                   [2.6,3.1,1.9]])
yields

# Increase yields of the second region by [0.2, 0.3, 0.1]
yields[1] += np.array([0.2, 0.3, 0.1])
yields

# Multiply the last column (Crop C) by 1.1
yields[:, -1] *= 1.1
yields

# Which crop has the highest average yield?
yields.mean(axis=0) 
yields

array([[2.5 , 3.  , 1.98],
       [3.  , 3.5 , 2.31],
       [3.1 , 2.9 , 2.42],
       [2.6 , 3.1 , 2.09]])

In [47]:
# 

scores = np.array([
    [85, 78, 92],
    [88, 74, 90],
    [70, 65, 80],
    [95, 89, 96]
])

# Extract scores of the top two students
top_two = scores[:2]
top_two

# Get all Math scores (first column)
math_scores = scores[:, 0]
print(math_scores)

# Find students who scored > 90 in Science (third column)
high_science = scores[scores[:, 2] > 90]
print(high_science)

scores[1: , 0:2]

[85 88 70 95]
[[85 78 92]
 [95 89 96]]

array([[88, 74],
       [70, 65],
       [95, 89]])

In [48]:
matrix = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
matrix[0]
matrix[:,1]
matrix[1: , 0:2]

array([[4, 5],
       [7, 8]])

In [49]:
# Boolean Indexing

arr=np.array([10,20,30,40,50])
arr[arr>25]

#array([30, 40, 50])

array([30, 40, 50])

In [60]:
# Scenario: Farm Crop Yield Analysis
# A farm tracks the yield (in kilograms) of three different crops — Wheat, Rice, and Corn — across four seasons (Spring, Summer, Autumn, Winter).
# The farm manager wants to analyze the data to make better decisions for next year.
# Tasks
# - Create a 2D array representing crop yields for 3 crops across 4 seasons.
# - Rows = crops
# - Columns = seasons
# - Increase all yields by 10% to account for improved irrigation.
# - Extract only Wheat’s yields (the first crop).
# - Find the average yield per crop across all seasons.
# - Identify yields greater than 3000 kg (to see which crops/seasons performed exceptionally well).

yields = np.array([[2000,4000,500,600],       # Wheat's
                   [7200,8900,910,4000],      # Rice
                   [3100,1220,1310,1400]])  # Corn
                   
yields

yields_increased = yields * 10
yields_increased

Extract_Wheat = yields_increased[0]
Extract_Wheat

Average_Yield = yields.mean()
Average_Yield

Yields_grt_than_3000 = yields[yields > 3000]
Yields_grt_than_3000

array([4000, 7200, 8900, 4000, 3100])

In [69]:
productions = np.array([[200,400,500,600],       # Gadgets
                   [720,890,910,400],            # Tools
                   [300,120,131,140]])           # Machines

Productions_Inc = productions * 5
Productions_Inc


Extract_First_Productions = productions[0]
Extract_First_Productions

Avg_production = productions.mean()
Avg_production

Production_grt_500 = productions[productions > 500]
Production_grt_500

array([600, 720, 890, 910])

In [74]:
# Pandas ---- Series and DataFrame

import pandas as pd

data = {
    "Name": ["A","B","C"],
    "Salary": [50000,40000,20000]
}

df = pd.DataFrame(data)
df

  Name  Salary
0    A   50000
1    B   40000
2    C   20000

In [75]:
type(df["Salary"])

pandas.core.series.Series

In [16]:
# Data Loading
import pandas as pd

df = pd.read_csv("sample_data2.csv")
df.head()
df.info()
df.describe()
df.fillna(0, inplace = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         15 non-null     int64
 1   Department          15 non-null     object
 2   Region              15 non-null     object
 3   Salary              15 non-null     int64
 4   Experience_Years    15 non-null     int64
 5   Performance_Rating  14 non-null     float64
 6   Monthly_Sales       14 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 972.0+ bytes

In [ ]:
# Filtering, Sorting, Grouping (Core Corporate Skill)

In [20]:
# Filtering

df[df["Salary"] > 20000]

,Employee_ID,Department,Region,Salary,Experience_Years,Performance_Rating,Monthly_Sales
0,1001,Sales,North,45000,2,4.0,120000.0
1,1002,Marketing,South,52000,3,3.0,98000.0
2,1003,Sales,East,47000,4,5.0,150000.0
3,1004,HR,West,40000,1,3.0,0.0
4,1005,IT,North,60000,5,4.0,0.0
5,1006,Sales,South,48000,3,4.0,130000.0
6,1007,Marketing,East,51000,2,2.0,87000.0
7,1008,IT,West,62000,6,5.0,0.0
8,1009,Sales,North,46000,3,4.0,125000.0
9,1010,HR,South,39000,2,3.0,0.0
10,1011,Sales,East,50000,4,5.0,140000.0
11,1012,Marketing,West,53000,3,0.0,92000.0
12,1013,IT,North,61000,5,4.0,0.0
13,1014,Sales,South,49000,3,4.0,135000.0
14,1015,HR,East,42000,2,3.0,0.0

In [17]:
# Sorting

df.sort_values("Monthly_Sales", ascending = False)

,Employee_ID,Department,Region,Salary,Experience_Years,Performance_Rating,Monthly_Sales
2,1003,Sales,East,47000,4,5.0,150000.0
10,1011,Sales,East,50000,4,5.0,140000.0
13,1014,Sales,South,49000,3,4.0,135000.0
5,1006,Sales,South,48000,3,4.0,130000.0
8,1009,Sales,North,46000,3,4.0,125000.0
0,1001,Sales,North,45000,2,4.0,120000.0
1,1002,Marketing,South,52000,3,3.0,98000.0
11,1012,Marketing,West,53000,3,0.0,92000.0
6,1007,Marketing,East,51000,2,2.0,87000.0
3,1004,HR,West,40000,1,3.0,0.0
4,1005,IT,North,60000,5,4.0,0.0
7,1008,IT,West,62000,6,5.0,0.0
9,1010,HR,South,39000,2,3.0,0.0
12,1013,IT,North,61000,5,4.0,0.0
14,1015,HR,East,42000,2,3.0,0.0

In [10]:
# Grouping 
df.groupby("Region")["Monthly_Sales"].sum()

Region
East     377000.0
North    245000.0
South    363000.0
West      92000.0
Name: Monthly_Sales, dtype: float64

In [ ]:
Scenario: Corporate Employee Performance Dashboard
A company tracks quarterly performance scores of employees across different departments.
The HR analytics team wants to analyze this dataset to identify top performers, departmental trends, and highlight exceptional scores.

Dataset
The dataset contains the following columns:
- Employee: Name of the employee
- Department: Department they belong to (Sales, HR, IT, Finance, etc.)
- Quarter: The quarter in which the performance score was recorded (Q1, Q2, Q3, Q4)
- Score: Performance score (numeric value)

Tasks
- Filtering (Core Corporate Skill)
- Find employees with Score > 90 (exceptional performers).
- Filter records for the Sales department only.
- Sorting (Power Moment)
- Sort employees by Score in descending order to rank performance.
- Sort by Department first, then Score to see departmental rankings.
- Grouping (Core Corporate Skill)
- Group by Department and calculate the average score per department.
- Group by Quarter and find the maximum score achieved in each quarter.

Business Context
- Filtering helps HR identify exceptional performers and focus on specific departments.
- Sorting creates clear performance rankings, useful for promotions or recognition programs.
- Grouping reveals departmental strengths and quarterly performance trends, guiding training and resource allocation.

In [24]:


import pandas as pd
df = pd.read_csv("Corporate_data.csv")
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    10 non-null     object
 1   Department  10 non-null     object
 2   Quarter     10 non-null     object
 3   Score       10 non-null     int64
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

           Score
count  10.000000
mean   85.300000
std     9.177872
min    70.000000
25%    78.500000
50%    86.500000
75%    91.500000
max    99.000000

In [26]:
df[df["Score"] > 90 ]    # 2nd answer  Find employees with Score > 90 (exceptional performers).

  Employee Department Quarter  Score
2     John         IT      Q1     92
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99

In [30]:
df[df["Department"] == "Sales"]  # Filter records for the Sales department only.

  Employee Department Quarter  Score
0     Amit      Sales      Q1     78
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99

In [ ]:
# Sorting (Power Moment)

In [34]:
# Sort employees by Score in descending order to rank performance.
df.sort_values("Score", ascending=True)

  Employee Department Quarter  Score
6     Alex         IT      Q2     70
9    Karan         IT      Q3     76
0     Amit      Sales      Q1     78
5    Meera         HR      Q2     80
1    Priya         HR      Q1     85
3     Sara    Finance      Q1     88
7     Ravi    Finance      Q2     90
2     John         IT      Q1     92
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99

In [36]:
# Sort by Department first, then Score to see departmental rankings.
df.sort_values(["Department", "Score"], ascending=[True, False])

  Employee Department Quarter  Score
7     Ravi    Finance      Q2     90
3     Sara    Finance      Q1     88
1    Priya         HR      Q1     85
5    Meera         HR      Q2     80
2     John         IT      Q1     92
9    Karan         IT      Q3     76
6     Alex         IT      Q2     70
8     Neha      Sales      Q3     99
4    David      Sales      Q2     95
0     Amit      Sales      Q1     78

In [ ]:
# GROUPING (Core Corporate Skill)

In [38]:
# Average Score Per Department
df.groupby("Department")["Score"].mean()

Department
Finance    89.000000
HR         82.500000
IT         79.333333
Sales      90.666667
Name: Score, dtype: float64

In [39]:
# Maximum Score Per Quarter
df.groupby("Quarter")["Score"].max()

Quarter
Q1    92
Q2    95
Q3    99
Name: Score, dtype: int64

In [ ]:
Scenario: E‑Commerce Customer & Sales Data Wrangling
An e‑commerce company wants to prepare its raw datasets for a machine learning project that predicts customer purchase behavior. The raw data comes from multiple sources (CSV exports from the sales system, Excel sheets from marketing, and logs from customer support).
The analytics team must clean, transform, and wrangle the data using Pandas before feeding it into ML/DL models.

Dataset Context
- Customers.csv → Customer ID, Name, Age, Region, Signup Date
- Sales.xlsx → Order ID, Customer ID, Product, Quantity, Price, Order Date
- Support.csv → Ticket ID, Customer ID, Issue Type, Resolution Time

Tasks
1. Data Loading
- Load CSV and Excel files into Pandas DataFrames.
- Inspect dataset shapes, column names, and missing values.
2. Array Operations & Broadcasting (NumPy Integration)
- Create a NumPy array of product prices and apply a 10% discount using broadcasting.
- Compute total revenue per order (Quantity × Price).
3. Indexing & Slicing
- Extract all orders placed in January 2025.
- Slice the first 10 rows of the sales dataset for quick inspection.
4. Filtering
- Filter customers from the “North” region.
- Identify orders with revenue greater than ₹10,000.
5. Sorting
- Sort customers by Signup Date (oldest to newest).
- Sort sales by Revenue in descending order.
6. Grouping
- Group sales by Region and calculate average revenue.
- Group support tickets by Issue Type and find average resolution time.
7. Data Wrangling Tasks
- Handle missing values (e.g., fill missing ages with median age).
- Rename columns for clarity (Cust_ID → CustomerID).
- Merge Customers, Sales, and Support datasets on CustomerID.
- Create new calculated fields:
- Customer Lifetime Value (CLV) = total revenue per customer.
- Average Resolution Time per Customer.
- Export the cleaned dataset to Cleaned_Data.csv for ML/DL model training.

In [59]:
import pandas as pd
customer=pd.read_csv("Customers1.csv")
supports=pd.read_csv("support1.csv")
sales=pd.read_csv("Sales1.csv")

In [60]:
# Inspect datasets

customer.head()
customer.info()
sales.head()
sales.info()
supports.head()
supports.info()

#  fill missing Age with median

#customers["Age"].fillna(customers["Age"].median(), inplace = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  8 non-null      object
 1   Name        8 non-null      object
 2   Age         7 non-null      float64
 3   Region      8 non-null      object
 4   SignupDate  8 non-null      object
dtypes: float64(1), object(4)
memory usage: 452.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     8 non-null      object
 1   CustomerID  8 non-null      object
 2   Product     8 non-null      object
 3   Quantity    8 non-null      int64
 4   Price       8 non-null      int64
 5   OrderDate   8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   TicketID        8 non-null      object
 1   CustomerID      8 non-null      object
 2   IssueType       8 non-null      object
 3   ResolutionTime  8 non-null      int64
dtypes: int64(1), object(3)
memory usage: 388.0+ bytes

In [82]:
 # Rename columns for clarity

customer.rename(columns={"CustomerID": "Cust_ID"}, inplace=True)
sales.rename(columns={"CustomerID": "Cust_ID"}, inplace=True)
support.rename(columns={"CustomerID": "Cust_ID"}, inplace=True)

print(customer.head())
print(sales.head())
print(support.head())

  Cust_ID   Name   Age Region  SignupDate
0    C001   Amit  28.0  North  2023-01-15
1    C002  Priya  35.0  South  2022-11-20
2    C003   John   NaN   East  2023-03-05
3    C004   Sara  42.0   West  2021-07-12
4    C005  David  30.0  North  2023-02-10
  OrderID Cust_ID Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001  Laptop         2  55000  2023-04-10          49500.0
1   O1002    C002  Mobile         1  25000  2023-04-12          22500.0
2   O1003    C003  Tablet         3  15000  2023-05-01          13500.0
3   O1004    C004  Laptop         1  60000  2023-05-15          54000.0
4   O1005    C005  Mobile         2  22000  2023-06-05          19800.0

   Revenue
0   110000
1    25000
2    45000
3    60000
4    44000
  TicketID Cust_ID       IssueType  ResolutionTime
0     T001    C001  Delivery Delay              48
1     T002    C002   Payment Issue              24
2     T003    C003  Product Defect              72
3     T004    C004  Delivery Delay              36
4     T005    C005   Payment Issue              12

In [68]:
# Numerical computations (NumPy integration)

# Apply 10% discount on product prices

sales["DiscountedPrice"] = sales["Price"] * 0.9
print(sales)

  OrderID Cust_ID     Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001      Laptop         2  55000  2023-04-10          49500.0
1   O1002    C002      Mobile         1  25000  2023-04-12          22500.0
2   O1003    C003      Tablet         3  15000  2023-05-01          13500.0
3   O1004    C004      Laptop         1  60000  2023-05-15          54000.0
4   O1005    C005      Mobile         2  22000  2023-06-05          19800.0
5   O1006    C006  Headphones         5   2000  2023-06-10           1800.0
6   O1007    C007      Laptop         1  58000  2023-07-02          52200.0
7   O1008    C008      Tablet         2  18000  2023-07-20          16200.0

   Revenue
0   110000
1    25000
2    45000
3    60000
4    44000
5    10000
6    58000
7    36000

In [67]:
# Compute revenue per order
sales["Revenue"] = sales["Quantity"] * sales["Price"]
print(sales)

  OrderID Cust_ID     Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001      Laptop         2  55000  2023-04-10          49500.0
1   O1002    C002      Mobile         1  25000  2023-04-12          22500.0
2   O1003    C003      Tablet         3  15000  2023-05-01          13500.0
3   O1004    C004      Laptop         1  60000  2023-05-15          54000.0
4   O1005    C005      Mobile         2  22000  2023-06-05          19800.0
5   O1006    C006  Headphones         5   2000  2023-06-10           1800.0
6   O1007    C007      Laptop         1  58000  2023-07-02          52200.0
7   O1008    C008      Tablet         2  18000  2023-07-20          16200.0

   Revenue
0   110000
1    25000
2    45000
3    60000
4    44000
5    10000
6    58000
7    36000

In [66]:
# 6. Indexing & Slicing

# Extract orders placed in April 2023
april_orders = sales[sales["OrderDate"].str.startswith("2023-04")]
print("\nApril Orders:\n", april_orders)

# Slice first 5 rows of sales
print("\nFirst 5 Sales Records:\n", sales.head())

April Orders:
   OrderID Cust_ID Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001  Laptop         2  55000  2023-04-10          49500.0
1   O1002    C002  Mobile         1  25000  2023-04-12          22500.0

   Revenue
0   110000
1    25000

First 5 Sales Records:
   OrderID Cust_ID Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001  Laptop         2  55000  2023-04-10          49500.0
1   O1002    C002  Mobile         1  25000  2023-04-12          22500.0
2   O1003    C003  Tablet         3  15000  2023-05-01          13500.0
3   O1004    C004  Laptop         1  60000  2023-05-15          54000.0
4   O1005    C005  Mobile         2  22000  2023-06-05          19800.0

   Revenue
0   110000
1    25000
2    45000
3    60000
4    44000

In [70]:

 # 7. Filtering

# Customers from North region
north_customers = customer[customer["Region"] == "North"]

# Orders with revenue > 50,000
high_value_orders = sales[sales["Revenue"] > 50000]

print("\nNorth Customers:\n", north_customers)
print("\nHigh Value Orders:\n", high_value_orders)

North Customers:
   Cust_ID   Name   Age Region  SignupDate
0    C001   Amit  28.0  North  2023-01-15
4    C005  David  30.0  North  2023-02-10

High Value Orders:
   OrderID Cust_ID Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001  Laptop         2  55000  2023-04-10          49500.0
3   O1004    C004  Laptop         1  60000  2023-05-15          54000.0
6   O1007    C007  Laptop         1  58000  2023-07-02          52200.0

   Revenue
0   110000
3    60000
6    58000

In [72]:
# 8. Sorting

# Sort customers by SignupDate
sorted_customers = customer.sort_values(by="SignupDate")

# Sort sales by Revenue descending
sorted_sales = sales.sort_values(by="Revenue", ascending=False)

print("\nSorted Customers:\n", sorted_customers)
print("\nSorted Sales:\n", sorted_sales)

Sorted Customers:
   Cust_ID   Name   Age Region  SignupDate
3    C004   Sara  42.0   West  2021-07-12
5    C006  Meera  27.0  South  2022-09-18
1    C002  Priya  35.0  South  2022-11-20
7    C008   Ravi  40.0   West  2022-12-01
0    C001   Amit  28.0  North  2023-01-15
6    C007   Alex  33.0   East  2023-01-25
4    C005  David  30.0  North  2023-02-10
2    C003   John   NaN   East  2023-03-05

Sorted Sales:
   OrderID Cust_ID     Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001      Laptop         2  55000  2023-04-10          49500.0
3   O1004    C004      Laptop         1  60000  2023-05-15          54000.0
6   O1007    C007      Laptop         1  58000  2023-07-02          52200.0
2   O1003    C003      Tablet         3  15000  2023-05-01          13500.0
4   O1005    C005      Mobile         2  22000  2023-06-05          19800.0
7   O1008    C008      Tablet         2  18000  2023-07-20          16200.0
1   O1002    C002      Mobile         1  25000  2023-04-12          22500.0
5   O1006    C006  Headphones         5   2000  2023-06-10           1800.0

   Revenue
0   110000
3    60000
6    58000
2    45000
4    44000
7    36000
1    25000
5    10000

In [74]:
# 9. Grouping

# Average revenue per product
avg_revenue_product = sales.groupby("Product")["Revenue"].mean()
print(avg_revenue_product)

Product
Headphones    10000.0
Laptop        76000.0
Mobile        34500.0
Tablet        40500.0
Name: Revenue, dtype: float64

In [75]:
# Average resolution time per issue type
avg_resolution_issue = support.groupby("IssueType")["ResolutionTime"].mean()

print("\nAverage Revenue per Product:\n", avg_revenue_product)
print("\nAverage Resolution Time per Issue Type:\n", avg_resolution_issue)

Average Revenue per Product:
 Product
Headphones    10000.0
Laptop        76000.0
Mobile        34500.0
Tablet        40500.0
Name: Revenue, dtype: float64

Average Resolution Time per Issue Type:
 IssueType
Delivery Delay    38.000000
Payment Issue     18.666667
Product Defect    66.000000
Name: ResolutionTime, dtype: float64

In [77]:

# 10. Merge datasets

merged_data = sales.merge(customer, on="Cust_ID").merge(support, on="Cust_ID")

print("\nMerged Dataset:\n", merged_data.head())

Merged Dataset:
   OrderID Cust_ID Product  Quantity  Price   OrderDate  DiscountedPrice  \
0   O1001    C001  Laptop         2  55000  2023-04-10          49500.0
1   O1002    C002  Mobile         1  25000  2023-04-12          22500.0
2   O1003    C003  Tablet         3  15000  2023-05-01          13500.0
3   O1004    C004  Laptop         1  60000  2023-05-15          54000.0
4   O1005    C005  Mobile         2  22000  2023-06-05          19800.0

   Revenue   Name   Age Region  SignupDate TicketID       IssueType  \
0   110000   Amit  28.0  North  2023-01-15     T001  Delivery Delay
1    25000  Priya  35.0  South  2022-11-20     T002   Payment Issue
2    45000   John   NaN   East  2023-03-05     T003  Product Defect
3    60000   Sara  42.0   West  2021-07-12     T004  Delivery Delay
4    44000  David  30.0  North  2023-02-10     T005   Payment Issue

   ResolutionTime
0              48
1              24
2              72
3              36
4              12

In [79]:
# 11. Create new calculated fields

# Customer Lifetime Value (CLV)
clv = sales.groupby("Cust_ID")["Revenue"].sum().reset_index()
clv.rename(columns={"Revenue": "CustomerLifetimeValue"}, inplace=True)

# Merge CLV back into customers
customers = customer.merge(clv, on="Cust_ID", how="left")

print("\nCustomers with CLV:\n", customers)

Customers with CLV:
   Cust_ID   Name   Age Region  SignupDate  CustomerLifetimeValue
0    C001   Amit  28.0  North  2023-01-15                 110000
1    C002  Priya  35.0  South  2022-11-20                  25000
2    C003   John   NaN   East  2023-03-05                  45000
3    C004   Sara  42.0   West  2021-07-12                  60000
4    C005  David  30.0  North  2023-02-10                  44000
5    C006  Meera  27.0  South  2022-09-18                  10000
6    C007   Alex  33.0   East  2023-01-25                  58000
7    C008   Ravi  40.0   West  2022-12-01                  36000

In [80]:
# 12. Export cleaned dataset

merged_data.to_csv("Cleaned_Data.csv", index=False)
print("\nCleaned dataset exported to Cleaned_Data.csv")

Cleaned dataset exported to Cleaned_Data.csv